// -------------------------------------------------------------
//
// Module: filter12
// Generated by MATLAB(R) 9.8 and Filter Design HDL Coder 3.1.7.
// Generated on: 2021-05-05 16:59:46
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// Name: filter12
// InputDataType: numerictype(1,13,12)
// TargetLanguage: Verilog
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form Symmetric FIR
// Filter Length     : 119
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s13,15 -> [-1.250000e-01 1.250000e-01)
// -------------------------------------------------------------
// Multipliers           : 53



`timescale 1 ns / 1 ns

module filter12
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                delay_pipeline,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [12:0] filter_in; //sfix13_En12
  input   signed [12:0] delay_pipeline [0:118] ; // sfix13_En12
  output  signed [32:0] filter_out; //sfix33_En27

////////////////////////////////////////////////////////////////
//Module Architecture: filter12
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [12:0] coeff1 = 13'b0000000000000; //sfix13_En15
  parameter signed [12:0] coeff2 = 13'b0000000000000; //sfix13_En15
  parameter signed [12:0] coeff3 = 13'b0000000000000; //sfix13_En15
  parameter signed [12:0] coeff4 = 13'b1111111111101; //sfix13_En15
  parameter signed [12:0] coeff5 = 13'b1111111111111; //sfix13_En15
  parameter signed [12:0] coeff6 = 13'b0000000001001; //sfix13_En15
  parameter signed [12:0] coeff7 = 13'b0000000001000; //sfix13_En15
  parameter signed [12:0] coeff8 = 13'b1111111110011; //sfix13_En15
  parameter signed [12:0] coeff9 = 13'b1111111101010; //sfix13_En15
  parameter signed [12:0] coeff10 = 13'b0000000001001; //sfix13_En15
  parameter signed [12:0] coeff11 = 13'b0000000101000; //sfix13_En15
  parameter signed [12:0] coeff12 = 13'b0000000001000; //sfix13_En15
  parameter signed [12:0] coeff13 = 13'b1111111001010; //sfix13_En15
  parameter signed [12:0] coeff14 = 13'b1111111011001; //sfix13_En15
  parameter signed [12:0] coeff15 = 13'b0000000110101; //sfix13_En15
  parameter signed [12:0] coeff16 = 13'b0000001001110; //sfix13_En15
  parameter signed [12:0] coeff17 = 13'b1111111100100; //sfix13_En15
  parameter signed [12:0] coeff18 = 13'b1111110010010; //sfix13_En15
  parameter signed [12:0] coeff19 = 13'b1111111101100; //sfix13_En15
  parameter signed [12:0] coeff20 = 13'b0000001110101; //sfix13_En15
  parameter signed [12:0] coeff21 = 13'b0000001001101; //sfix13_En15
  parameter signed [12:0] coeff22 = 13'b1111110100101; //sfix13_En15
  parameter signed [12:0] coeff23 = 13'b1111110000110; //sfix13_En15
  parameter signed [12:0] coeff24 = 13'b0000000100101; //sfix13_En15
  parameter signed [12:0] coeff25 = 13'b0000010000100; //sfix13_En15
  parameter signed [12:0] coeff26 = 13'b0000000010110; //sfix13_En15
  parameter signed [12:0] coeff27 = 13'b1111110011100; //sfix13_En15
  parameter signed [12:0] coeff28 = 13'b1111111001011; //sfix13_En15
  parameter signed [12:0] coeff29 = 13'b0000000101010; //sfix13_En15
  parameter signed [12:0] coeff30 = 13'b0000000011110; //sfix13_En15
  parameter signed [12:0] coeff31 = 13'b0000000000001; //sfix13_En15
  parameter signed [12:0] coeff32 = 13'b0000000110000; //sfix13_En15
  parameter signed [12:0] coeff33 = 13'b0000000010010; //sfix13_En15
  parameter signed [12:0] coeff34 = 13'b1111101110001; //sfix13_En15
  parameter signed [12:0] coeff35 = 13'b1111101111101; //sfix13_En15
  parameter signed [12:0] coeff36 = 13'b0000010111110; //sfix13_En15
  parameter signed [12:0] coeff37 = 13'b0000101001000; //sfix13_En15
  parameter signed [12:0] coeff38 = 13'b1111110001101; //sfix13_En15
  parameter signed [12:0] coeff39 = 13'b1110111011111; //sfix13_En15
  parameter signed [12:0] coeff40 = 13'b1111110000011; //sfix13_En15
  parameter signed [12:0] coeff41 = 13'b0001010100100; //sfix13_En15
  parameter signed [12:0] coeff42 = 13'b0000111111110; //sfix13_En15
  parameter signed [12:0] coeff43 = 13'b1110110011100; //sfix13_En15
  parameter signed [12:0] coeff44 = 13'b1110001001101; //sfix13_En15
  parameter signed [12:0] coeff45 = 13'b0000100011101; //sfix13_En15
  parameter signed [12:0] coeff46 = 13'b0010100000101; //sfix13_En15
  parameter signed [12:0] coeff47 = 13'b0000100011110; //sfix13_En15
  parameter signed [12:0] coeff48 = 13'b1101010101011; //sfix13_En15
  parameter signed [12:0] coeff49 = 13'b1110000101001; //sfix13_En15
  parameter signed [12:0] coeff50 = 13'b0010000111100; //sfix13_En15
  parameter signed [12:0] coeff51 = 13'b0011001001111; //sfix13_En15
  parameter signed [12:0] coeff52 = 13'b1111001000111; //sfix13_En15
  parameter signed [12:0] coeff53 = 13'b1100001001100; //sfix13_En15
  parameter signed [12:0] coeff54 = 13'b1111001001010; //sfix13_En15
  parameter signed [12:0] coeff55 = 13'b0011101110000; //sfix13_En15
  parameter signed [12:0] coeff56 = 13'b0010100111000; //sfix13_En15
  parameter signed [12:0] coeff57 = 13'b1101010011110; //sfix13_En15
  parameter signed [12:0] coeff58 = 13'b1100000101011; //sfix13_En15
  parameter signed [12:0] coeff59 = 13'b0000111110111; //sfix13_En15
  parameter signed [12:0] coeff60 = 13'b0100011001101; //sfix13_En15

  // Signals
  wire signed [13:0] tapsum4; // sfix14_En12
  wire signed [12:0] add_signext; // sfix13_En12
  wire signed [12:0] add_signext_1; // sfix13_En12
  wire signed [13:0] tapsum_mcand; // sfix14_En12
  wire signed [13:0] tapsum5; // sfix14_En12
  wire signed [12:0] add_signext_2; // sfix13_En12
  wire signed [12:0] add_signext_3; // sfix13_En12
  wire signed [13:0] tapsum_mcand_1; // sfix14_En12
  wire signed [13:0] tapsum6; // sfix14_En12
  wire signed [12:0] add_signext_4; // sfix13_En12
  wire signed [12:0] add_signext_5; // sfix13_En12
  wire signed [13:0] tapsum_mcand_2; // sfix14_En12
  wire signed [13:0] tapsum7; // sfix14_En12
  wire signed [12:0] add_signext_6; // sfix13_En12
  wire signed [12:0] add_signext_7; // sfix13_En12
  wire signed [13:0] tapsum_mcand_3; // sfix14_En12
  wire signed [13:0] tapsum8; // sfix14_En12
  wire signed [12:0] add_signext_8; // sfix13_En12
  wire signed [12:0] add_signext_9; // sfix13_En12
  wire signed [13:0] tapsum_mcand_4; // sfix14_En12
  wire signed [13:0] tapsum9; // sfix14_En12
  wire signed [12:0] add_signext_10; // sfix13_En12
  wire signed [12:0] add_signext_11; // sfix13_En12
  wire signed [13:0] tapsum_mcand_5; // sfix14_En12
  wire signed [13:0] tapsum10; // sfix14_En12
  wire signed [12:0] add_signext_12; // sfix13_En12
  wire signed [12:0] add_signext_13; // sfix13_En12
  wire signed [13:0] tapsum_mcand_6; // sfix14_En12
  wire signed [13:0] tapsum11; // sfix14_En12
  wire signed [12:0] add_signext_14; // sfix13_En12
  wire signed [12:0] add_signext_15; // sfix13_En12
  wire signed [13:0] tapsum_mcand_7; // sfix14_En12
  wire signed [13:0] tapsum12; // sfix14_En12
  wire signed [12:0] add_signext_16; // sfix13_En12
  wire signed [12:0] add_signext_17; // sfix13_En12
  wire signed [13:0] tapsum_mcand_8; // sfix14_En12
  wire signed [13:0] tapsum13; // sfix14_En12
  wire signed [12:0] add_signext_18; // sfix13_En12
  wire signed [12:0] add_signext_19; // sfix13_En12
  wire signed [13:0] tapsum_mcand_9; // sfix14_En12
  wire signed [13:0] tapsum14; // sfix14_En12
  wire signed [12:0] add_signext_20; // sfix13_En12
  wire signed [12:0] add_signext_21; // sfix13_En12
  wire signed [13:0] tapsum_mcand_10; // sfix14_En12
  wire signed [13:0] tapsum15; // sfix14_En12
  wire signed [12:0] add_signext_22; // sfix13_En12
  wire signed [12:0] add_signext_23; // sfix13_En12
  wire signed [13:0] tapsum_mcand_11; // sfix14_En12
  wire signed [13:0] tapsum16; // sfix14_En12
  wire signed [12:0] add_signext_24; // sfix13_En12
  wire signed [12:0] add_signext_25; // sfix13_En12
  wire signed [13:0] tapsum_mcand_12; // sfix14_En12
  wire signed [13:0] tapsum17; // sfix14_En12
  wire signed [12:0] add_signext_26; // sfix13_En12
  wire signed [12:0] add_signext_27; // sfix13_En12
  wire signed [13:0] tapsum_mcand_13; // sfix14_En12
  wire signed [13:0] tapsum18; // sfix14_En12
  wire signed [12:0] add_signext_28; // sfix13_En12
  wire signed [12:0] add_signext_29; // sfix13_En12
  wire signed [13:0] tapsum_mcand_14; // sfix14_En12
  wire signed [13:0] tapsum19; // sfix14_En12
  wire signed [12:0] add_signext_30; // sfix13_En12
  wire signed [12:0] add_signext_31; // sfix13_En12
  wire signed [13:0] tapsum_mcand_15; // sfix14_En12
  wire signed [13:0] tapsum20; // sfix14_En12
  wire signed [12:0] add_signext_32; // sfix13_En12
  wire signed [12:0] add_signext_33; // sfix13_En12
  wire signed [13:0] tapsum_mcand_16; // sfix14_En12
  wire signed [13:0] tapsum21; // sfix14_En12
  wire signed [12:0] add_signext_34; // sfix13_En12
  wire signed [12:0] add_signext_35; // sfix13_En12
  wire signed [13:0] tapsum_mcand_17; // sfix14_En12
  wire signed [13:0] tapsum22; // sfix14_En12
  wire signed [12:0] add_signext_36; // sfix13_En12
  wire signed [12:0] add_signext_37; // sfix13_En12
  wire signed [13:0] tapsum_mcand_18; // sfix14_En12
  wire signed [13:0] tapsum23; // sfix14_En12
  wire signed [12:0] add_signext_38; // sfix13_En12
  wire signed [12:0] add_signext_39; // sfix13_En12
  wire signed [13:0] tapsum_mcand_19; // sfix14_En12
  wire signed [13:0] tapsum24; // sfix14_En12
  wire signed [12:0] add_signext_40; // sfix13_En12
  wire signed [12:0] add_signext_41; // sfix13_En12
  wire signed [13:0] tapsum_mcand_20; // sfix14_En12
  wire signed [13:0] tapsum25; // sfix14_En12
  wire signed [12:0] add_signext_42; // sfix13_En12
  wire signed [12:0] add_signext_43; // sfix13_En12
  wire signed [13:0] tapsum_mcand_21; // sfix14_En12
  wire signed [13:0] tapsum26; // sfix14_En12
  wire signed [12:0] add_signext_44; // sfix13_En12
  wire signed [12:0] add_signext_45; // sfix13_En12
  wire signed [13:0] tapsum_mcand_22; // sfix14_En12
  wire signed [13:0] tapsum27; // sfix14_En12
  wire signed [12:0] add_signext_46; // sfix13_En12
  wire signed [12:0] add_signext_47; // sfix13_En12
  wire signed [13:0] tapsum_mcand_23; // sfix14_En12
  wire signed [13:0] tapsum28; // sfix14_En12
  wire signed [12:0] add_signext_48; // sfix13_En12
  wire signed [12:0] add_signext_49; // sfix13_En12
  wire signed [13:0] tapsum_mcand_24; // sfix14_En12
  wire signed [13:0] tapsum29; // sfix14_En12
  wire signed [12:0] add_signext_50; // sfix13_En12
  wire signed [12:0] add_signext_51; // sfix13_En12
  wire signed [13:0] tapsum_mcand_25; // sfix14_En12
  wire signed [13:0] tapsum30; // sfix14_En12
  wire signed [12:0] add_signext_52; // sfix13_En12
  wire signed [12:0] add_signext_53; // sfix13_En12
  wire signed [13:0] tapsum_mcand_26; // sfix14_En12
  wire signed [13:0] tapsum31; // sfix14_En12
  wire signed [12:0] add_signext_54; // sfix13_En12
  wire signed [12:0] add_signext_55; // sfix13_En12
  wire signed [13:0] tapsum_mcand_27; // sfix14_En12
  wire signed [13:0] tapsum32; // sfix14_En12
  wire signed [12:0] add_signext_56; // sfix13_En12
  wire signed [12:0] add_signext_57; // sfix13_En12
  wire signed [13:0] tapsum_mcand_28; // sfix14_En12
  wire signed [13:0] tapsum33; // sfix14_En12
  wire signed [12:0] add_signext_58; // sfix13_En12
  wire signed [12:0] add_signext_59; // sfix13_En12
  wire signed [13:0] tapsum_mcand_29; // sfix14_En12
  wire signed [13:0] tapsum34; // sfix14_En12
  wire signed [12:0] add_signext_60; // sfix13_En12
  wire signed [12:0] add_signext_61; // sfix13_En12
  wire signed [13:0] tapsum_mcand_30; // sfix14_En12
  wire signed [13:0] tapsum35; // sfix14_En12
  wire signed [12:0] add_signext_62; // sfix13_En12
  wire signed [12:0] add_signext_63; // sfix13_En12
  wire signed [13:0] tapsum_mcand_31; // sfix14_En12
  wire signed [13:0] tapsum36; // sfix14_En12
  wire signed [12:0] add_signext_64; // sfix13_En12
  wire signed [12:0] add_signext_65; // sfix13_En12
  wire signed [13:0] tapsum_mcand_32; // sfix14_En12
  wire signed [13:0] tapsum37; // sfix14_En12
  wire signed [12:0] add_signext_66; // sfix13_En12
  wire signed [12:0] add_signext_67; // sfix13_En12
  wire signed [13:0] tapsum_mcand_33; // sfix14_En12
  wire signed [13:0] tapsum38; // sfix14_En12
  wire signed [12:0] add_signext_68; // sfix13_En12
  wire signed [12:0] add_signext_69; // sfix13_En12
  wire signed [13:0] tapsum_mcand_34; // sfix14_En12
  wire signed [13:0] tapsum39; // sfix14_En12
  wire signed [12:0] add_signext_70; // sfix13_En12
  wire signed [12:0] add_signext_71; // sfix13_En12
  wire signed [13:0] tapsum_mcand_35; // sfix14_En12
  wire signed [13:0] tapsum40; // sfix14_En12
  wire signed [12:0] add_signext_72; // sfix13_En12
  wire signed [12:0] add_signext_73; // sfix13_En12
  wire signed [13:0] tapsum_mcand_36; // sfix14_En12
  wire signed [13:0] tapsum41; // sfix14_En12
  wire signed [12:0] add_signext_74; // sfix13_En12
  wire signed [12:0] add_signext_75; // sfix13_En12
  wire signed [13:0] tapsum_mcand_37; // sfix14_En12
  wire signed [13:0] tapsum42; // sfix14_En12
  wire signed [12:0] add_signext_76; // sfix13_En12
  wire signed [12:0] add_signext_77; // sfix13_En12
  wire signed [13:0] tapsum_mcand_38; // sfix14_En12
  wire signed [13:0] tapsum43; // sfix14_En12
  wire signed [12:0] add_signext_78; // sfix13_En12
  wire signed [12:0] add_signext_79; // sfix13_En12
  wire signed [13:0] tapsum_mcand_39; // sfix14_En12
  wire signed [13:0] tapsum44; // sfix14_En12
  wire signed [12:0] add_signext_80; // sfix13_En12
  wire signed [12:0] add_signext_81; // sfix13_En12
  wire signed [13:0] tapsum_mcand_40; // sfix14_En12
  wire signed [13:0] tapsum45; // sfix14_En12
  wire signed [12:0] add_signext_82; // sfix13_En12
  wire signed [12:0] add_signext_83; // sfix13_En12
  wire signed [13:0] tapsum_mcand_41; // sfix14_En12
  wire signed [13:0] tapsum46; // sfix14_En12
  wire signed [12:0] add_signext_84; // sfix13_En12
  wire signed [12:0] add_signext_85; // sfix13_En12
  wire signed [13:0] tapsum_mcand_42; // sfix14_En12
  wire signed [13:0] tapsum47; // sfix14_En12
  wire signed [12:0] add_signext_86; // sfix13_En12
  wire signed [12:0] add_signext_87; // sfix13_En12
  wire signed [13:0] tapsum_mcand_43; // sfix14_En12
  wire signed [13:0] tapsum48; // sfix14_En12
  wire signed [12:0] add_signext_88; // sfix13_En12
  wire signed [12:0] add_signext_89; // sfix13_En12
  wire signed [13:0] tapsum_mcand_44; // sfix14_En12
  wire signed [13:0] tapsum49; // sfix14_En12
  wire signed [12:0] add_signext_90; // sfix13_En12
  wire signed [12:0] add_signext_91; // sfix13_En12
  wire signed [13:0] tapsum_mcand_45; // sfix14_En12
  wire signed [13:0] tapsum50; // sfix14_En12
  wire signed [12:0] add_signext_92; // sfix13_En12
  wire signed [12:0] add_signext_93; // sfix13_En12
  wire signed [13:0] tapsum_mcand_46; // sfix14_En12
  wire signed [13:0] tapsum51; // sfix14_En12
  wire signed [12:0] add_signext_94; // sfix13_En12
  wire signed [12:0] add_signext_95; // sfix13_En12
  wire signed [13:0] tapsum_mcand_47; // sfix14_En12
  wire signed [13:0] tapsum52; // sfix14_En12
  wire signed [12:0] add_signext_96; // sfix13_En12
  wire signed [12:0] add_signext_97; // sfix13_En12
  wire signed [13:0] tapsum_mcand_48; // sfix14_En12
  wire signed [13:0] tapsum53; // sfix14_En12
  wire signed [12:0] add_signext_98; // sfix13_En12
  wire signed [12:0] add_signext_99; // sfix13_En12
  wire signed [13:0] tapsum_mcand_49; // sfix14_En12
  wire signed [13:0] tapsum54; // sfix14_En12
  wire signed [12:0] add_signext_100; // sfix13_En12
  wire signed [12:0] add_signext_101; // sfix13_En12
  wire signed [13:0] tapsum_mcand_50; // sfix14_En12
  wire signed [13:0] tapsum55; // sfix14_En12
  wire signed [12:0] add_signext_102; // sfix13_En12
  wire signed [12:0] add_signext_103; // sfix13_En12
  wire signed [13:0] tapsum_mcand_51; // sfix14_En12
  wire signed [13:0] tapsum56; // sfix14_En12
  wire signed [12:0] add_signext_104; // sfix13_En12
  wire signed [12:0] add_signext_105; // sfix13_En12
  wire signed [13:0] tapsum_mcand_52; // sfix14_En12
  wire signed [13:0] tapsum57; // sfix14_En12
  wire signed [12:0] add_signext_106; // sfix13_En12
  wire signed [12:0] add_signext_107; // sfix13_En12
  wire signed [13:0] tapsum_mcand_53; // sfix14_En12
  wire signed [13:0] tapsum58; // sfix14_En12
  wire signed [12:0] add_signext_108; // sfix13_En12
  wire signed [12:0] add_signext_109; // sfix13_En12
  wire signed [13:0] tapsum_mcand_54; // sfix14_En12
  wire signed [13:0] tapsum59; // sfix14_En12
  wire signed [12:0] add_signext_110; // sfix13_En12
  wire signed [12:0] add_signext_111; // sfix13_En12
  wire signed [13:0] tapsum_mcand_55; // sfix14_En12
  wire signed [26:0] product60; // sfix27_En27
  wire signed [25:0] mul_temp; // sfix26_En27
  wire signed [26:0] product59; // sfix27_En27
  wire signed [26:0] product58; // sfix27_En27
  wire signed [26:0] product57; // sfix27_En27
  wire signed [26:0] product56; // sfix27_En27
  wire signed [26:0] product55; // sfix27_En27
  wire signed [26:0] product54; // sfix27_En27
  wire signed [26:0] product53; // sfix27_En27
  wire signed [26:0] product52; // sfix27_En27
  wire signed [26:0] product51; // sfix27_En27
  wire signed [26:0] product50; // sfix27_En27
  wire signed [26:0] product49; // sfix27_En27
  wire signed [26:0] product48; // sfix27_En27
  wire signed [26:0] product47; // sfix27_En27
  wire signed [26:0] product46; // sfix27_En27
  wire signed [26:0] product45; // sfix27_En27
  wire signed [26:0] product44; // sfix27_En27
  wire signed [26:0] product43; // sfix27_En27
  wire signed [26:0] product42; // sfix27_En27
  wire signed [26:0] product41; // sfix27_En27
  wire signed [26:0] product40; // sfix27_En27
  wire signed [26:0] product39; // sfix27_En27
  wire signed [26:0] product38; // sfix27_En27
  wire signed [26:0] product37; // sfix27_En27
  wire signed [26:0] product36; // sfix27_En27
  wire signed [26:0] product35; // sfix27_En27
  wire signed [26:0] product34; // sfix27_En27
  wire signed [26:0] product33; // sfix27_En27
  wire signed [26:0] product32; // sfix27_En27
  wire signed [26:0] product31; // sfix27_En27
  wire signed [26:0] product30; // sfix27_En27
  wire signed [26:0] product29; // sfix27_En27
  wire signed [26:0] product28; // sfix27_En27
  wire signed [26:0] product27; // sfix27_En27
  wire signed [26:0] product26; // sfix27_En27
  wire signed [26:0] product25; // sfix27_En27
  wire signed [26:0] product24; // sfix27_En27
  wire signed [26:0] product23; // sfix27_En27
  wire signed [26:0] product22; // sfix27_En27
  wire signed [26:0] product21; // sfix27_En27
  wire signed [26:0] product20; // sfix27_En27
  wire signed [26:0] product19; // sfix27_En27
  wire signed [26:0] product18; // sfix27_En27
  wire signed [26:0] product17; // sfix27_En27
  wire signed [26:0] product16; // sfix27_En27
  wire signed [26:0] product15; // sfix27_En27
  wire signed [26:0] product14; // sfix27_En27
  wire signed [26:0] product13; // sfix27_En27
  wire signed [26:0] product12; // sfix27_En27
  wire signed [26:0] product11; // sfix27_En27
  wire signed [26:0] product10; // sfix27_En27
  wire signed [26:0] product9; // sfix27_En27
  wire signed [26:0] product8; // sfix27_En27
  wire signed [26:0] product7; // sfix27_En27
  wire signed [26:0] product6; // sfix27_En27
  wire signed [26:0] product5; // sfix27_En27
  wire signed [14:0] mulpwr2_temp; // sfix15_En12
  wire signed [26:0] product4; // sfix27_En27
  wire signed [32:0] sum1; // sfix33_En27
  wire signed [26:0] add_signext_112; // sfix27_En27
  wire signed [26:0] add_signext_113; // sfix27_En27
  wire signed [27:0] add_temp; // sfix28_En27
  wire signed [32:0] sum2; // sfix33_En27
  wire signed [32:0] add_signext_114; // sfix33_En27
  wire signed [32:0] add_signext_115; // sfix33_En27
  wire signed [33:0] add_temp_1; // sfix34_En27
  wire signed [32:0] sum3; // sfix33_En27
  wire signed [32:0] add_signext_116; // sfix33_En27
  wire signed [32:0] add_signext_117; // sfix33_En27
  wire signed [33:0] add_temp_2; // sfix34_En27
  wire signed [32:0] sum4; // sfix33_En27
  wire signed [32:0] add_signext_118; // sfix33_En27
  wire signed [32:0] add_signext_119; // sfix33_En27
  wire signed [33:0] add_temp_3; // sfix34_En27
  wire signed [32:0] sum5; // sfix33_En27
  wire signed [32:0] add_signext_120; // sfix33_En27
  wire signed [32:0] add_signext_121; // sfix33_En27
  wire signed [33:0] add_temp_4; // sfix34_En27
  wire signed [32:0] sum6; // sfix33_En27
  wire signed [32:0] add_signext_122; // sfix33_En27
  wire signed [32:0] add_signext_123; // sfix33_En27
  wire signed [33:0] add_temp_5; // sfix34_En27
  wire signed [32:0] sum7; // sfix33_En27
  wire signed [32:0] add_signext_124; // sfix33_En27
  wire signed [32:0] add_signext_125; // sfix33_En27
  wire signed [33:0] add_temp_6; // sfix34_En27
  wire signed [32:0] sum8; // sfix33_En27
  wire signed [32:0] add_signext_126; // sfix33_En27
  wire signed [32:0] add_signext_127; // sfix33_En27
  wire signed [33:0] add_temp_7; // sfix34_En27
  wire signed [32:0] sum9; // sfix33_En27
  wire signed [32:0] add_signext_128; // sfix33_En27
  wire signed [32:0] add_signext_129; // sfix33_En27
  wire signed [33:0] add_temp_8; // sfix34_En27
  wire signed [32:0] sum10; // sfix33_En27
  wire signed [32:0] add_signext_130; // sfix33_En27
  wire signed [32:0] add_signext_131; // sfix33_En27
  wire signed [33:0] add_temp_9; // sfix34_En27
  wire signed [32:0] sum11; // sfix33_En27
  wire signed [32:0] add_signext_132; // sfix33_En27
  wire signed [32:0] add_signext_133; // sfix33_En27
  wire signed [33:0] add_temp_10; // sfix34_En27
  wire signed [32:0] sum12; // sfix33_En27
  wire signed [32:0] add_signext_134; // sfix33_En27
  wire signed [32:0] add_signext_135; // sfix33_En27
  wire signed [33:0] add_temp_11; // sfix34_En27
  wire signed [32:0] sum13; // sfix33_En27
  wire signed [32:0] add_signext_136; // sfix33_En27
  wire signed [32:0] add_signext_137; // sfix33_En27
  wire signed [33:0] add_temp_12; // sfix34_En27
  wire signed [32:0] sum14; // sfix33_En27
  wire signed [32:0] add_signext_138; // sfix33_En27
  wire signed [32:0] add_signext_139; // sfix33_En27
  wire signed [33:0] add_temp_13; // sfix34_En27
  wire signed [32:0] sum15; // sfix33_En27
  wire signed [32:0] add_signext_140; // sfix33_En27
  wire signed [32:0] add_signext_141; // sfix33_En27
  wire signed [33:0] add_temp_14; // sfix34_En27
  wire signed [32:0] sum16; // sfix33_En27
  wire signed [32:0] add_signext_142; // sfix33_En27
  wire signed [32:0] add_signext_143; // sfix33_En27
  wire signed [33:0] add_temp_15; // sfix34_En27
  wire signed [32:0] sum17; // sfix33_En27
  wire signed [32:0] add_signext_144; // sfix33_En27
  wire signed [32:0] add_signext_145; // sfix33_En27
  wire signed [33:0] add_temp_16; // sfix34_En27
  wire signed [32:0] sum18; // sfix33_En27
  wire signed [32:0] add_signext_146; // sfix33_En27
  wire signed [32:0] add_signext_147; // sfix33_En27
  wire signed [33:0] add_temp_17; // sfix34_En27
  wire signed [32:0] sum19; // sfix33_En27
  wire signed [32:0] add_signext_148; // sfix33_En27
  wire signed [32:0] add_signext_149; // sfix33_En27
  wire signed [33:0] add_temp_18; // sfix34_En27
  wire signed [32:0] sum20; // sfix33_En27
  wire signed [32:0] add_signext_150; // sfix33_En27
  wire signed [32:0] add_signext_151; // sfix33_En27
  wire signed [33:0] add_temp_19; // sfix34_En27
  wire signed [32:0] sum21; // sfix33_En27
  wire signed [32:0] add_signext_152; // sfix33_En27
  wire signed [32:0] add_signext_153; // sfix33_En27
  wire signed [33:0] add_temp_20; // sfix34_En27
  wire signed [32:0] sum22; // sfix33_En27
  wire signed [32:0] add_signext_154; // sfix33_En27
  wire signed [32:0] add_signext_155; // sfix33_En27
  wire signed [33:0] add_temp_21; // sfix34_En27
  wire signed [32:0] sum23; // sfix33_En27
  wire signed [32:0] add_signext_156; // sfix33_En27
  wire signed [32:0] add_signext_157; // sfix33_En27
  wire signed [33:0] add_temp_22; // sfix34_En27
  wire signed [32:0] sum24; // sfix33_En27
  wire signed [32:0] add_signext_158; // sfix33_En27
  wire signed [32:0] add_signext_159; // sfix33_En27
  wire signed [33:0] add_temp_23; // sfix34_En27
  wire signed [32:0] sum25; // sfix33_En27
  wire signed [32:0] add_signext_160; // sfix33_En27
  wire signed [32:0] add_signext_161; // sfix33_En27
  wire signed [33:0] add_temp_24; // sfix34_En27
  wire signed [32:0] sum26; // sfix33_En27
  wire signed [32:0] add_signext_162; // sfix33_En27
  wire signed [32:0] add_signext_163; // sfix33_En27
  wire signed [33:0] add_temp_25; // sfix34_En27
  wire signed [32:0] sum27; // sfix33_En27
  wire signed [32:0] add_signext_164; // sfix33_En27
  wire signed [32:0] add_signext_165; // sfix33_En27
  wire signed [33:0] add_temp_26; // sfix34_En27
  wire signed [32:0] sum28; // sfix33_En27
  wire signed [32:0] add_signext_166; // sfix33_En27
  wire signed [32:0] add_signext_167; // sfix33_En27
  wire signed [33:0] add_temp_27; // sfix34_En27
  wire signed [32:0] sum29; // sfix33_En27
  wire signed [32:0] add_signext_168; // sfix33_En27
  wire signed [32:0] add_signext_169; // sfix33_En27
  wire signed [33:0] add_temp_28; // sfix34_En27
  wire signed [32:0] sum30; // sfix33_En27
  wire signed [32:0] add_signext_170; // sfix33_En27
  wire signed [32:0] add_signext_171; // sfix33_En27
  wire signed [33:0] add_temp_29; // sfix34_En27
  wire signed [32:0] sum31; // sfix33_En27
  wire signed [32:0] add_signext_172; // sfix33_En27
  wire signed [32:0] add_signext_173; // sfix33_En27
  wire signed [33:0] add_temp_30; // sfix34_En27
  wire signed [32:0] sum32; // sfix33_En27
  wire signed [32:0] add_signext_174; // sfix33_En27
  wire signed [32:0] add_signext_175; // sfix33_En27
  wire signed [33:0] add_temp_31; // sfix34_En27
  wire signed [32:0] sum33; // sfix33_En27
  wire signed [32:0] add_signext_176; // sfix33_En27
  wire signed [32:0] add_signext_177; // sfix33_En27
  wire signed [33:0] add_temp_32; // sfix34_En27
  wire signed [32:0] sum34; // sfix33_En27
  wire signed [32:0] add_signext_178; // sfix33_En27
  wire signed [32:0] add_signext_179; // sfix33_En27
  wire signed [33:0] add_temp_33; // sfix34_En27
  wire signed [32:0] sum35; // sfix33_En27
  wire signed [32:0] add_signext_180; // sfix33_En27
  wire signed [32:0] add_signext_181; // sfix33_En27
  wire signed [33:0] add_temp_34; // sfix34_En27
  wire signed [32:0] sum36; // sfix33_En27
  wire signed [32:0] add_signext_182; // sfix33_En27
  wire signed [32:0] add_signext_183; // sfix33_En27
  wire signed [33:0] add_temp_35; // sfix34_En27
  wire signed [32:0] sum37; // sfix33_En27
  wire signed [32:0] add_signext_184; // sfix33_En27
  wire signed [32:0] add_signext_185; // sfix33_En27
  wire signed [33:0] add_temp_36; // sfix34_En27
  wire signed [32:0] sum38; // sfix33_En27
  wire signed [32:0] add_signext_186; // sfix33_En27
  wire signed [32:0] add_signext_187; // sfix33_En27
  wire signed [33:0] add_temp_37; // sfix34_En27
  wire signed [32:0] sum39; // sfix33_En27
  wire signed [32:0] add_signext_188; // sfix33_En27
  wire signed [32:0] add_signext_189; // sfix33_En27
  wire signed [33:0] add_temp_38; // sfix34_En27
  wire signed [32:0] sum40; // sfix33_En27
  wire signed [32:0] add_signext_190; // sfix33_En27
  wire signed [32:0] add_signext_191; // sfix33_En27
  wire signed [33:0] add_temp_39; // sfix34_En27
  wire signed [32:0] sum41; // sfix33_En27
  wire signed [32:0] add_signext_192; // sfix33_En27
  wire signed [32:0] add_signext_193; // sfix33_En27
  wire signed [33:0] add_temp_40; // sfix34_En27
  wire signed [32:0] sum42; // sfix33_En27
  wire signed [32:0] add_signext_194; // sfix33_En27
  wire signed [32:0] add_signext_195; // sfix33_En27
  wire signed [33:0] add_temp_41; // sfix34_En27
  wire signed [32:0] sum43; // sfix33_En27
  wire signed [32:0] add_signext_196; // sfix33_En27
  wire signed [32:0] add_signext_197; // sfix33_En27
  wire signed [33:0] add_temp_42; // sfix34_En27
  wire signed [32:0] sum44; // sfix33_En27
  wire signed [32:0] add_signext_198; // sfix33_En27
  wire signed [32:0] add_signext_199; // sfix33_En27
  wire signed [33:0] add_temp_43; // sfix34_En27
  wire signed [32:0] sum45; // sfix33_En27
  wire signed [32:0] add_signext_200; // sfix33_En27
  wire signed [32:0] add_signext_201; // sfix33_En27
  wire signed [33:0] add_temp_44; // sfix34_En27
  wire signed [32:0] sum46; // sfix33_En27
  wire signed [32:0] add_signext_202; // sfix33_En27
  wire signed [32:0] add_signext_203; // sfix33_En27
  wire signed [33:0] add_temp_45; // sfix34_En27
  wire signed [32:0] sum47; // sfix33_En27
  wire signed [32:0] add_signext_204; // sfix33_En27
  wire signed [32:0] add_signext_205; // sfix33_En27
  wire signed [33:0] add_temp_46; // sfix34_En27
  wire signed [32:0] sum48; // sfix33_En27
  wire signed [32:0] add_signext_206; // sfix33_En27
  wire signed [32:0] add_signext_207; // sfix33_En27
  wire signed [33:0] add_temp_47; // sfix34_En27
  wire signed [32:0] sum49; // sfix33_En27
  wire signed [32:0] add_signext_208; // sfix33_En27
  wire signed [32:0] add_signext_209; // sfix33_En27
  wire signed [33:0] add_temp_48; // sfix34_En27
  wire signed [32:0] sum50; // sfix33_En27
  wire signed [32:0] add_signext_210; // sfix33_En27
  wire signed [32:0] add_signext_211; // sfix33_En27
  wire signed [33:0] add_temp_49; // sfix34_En27
  wire signed [32:0] sum51; // sfix33_En27
  wire signed [32:0] add_signext_212; // sfix33_En27
  wire signed [32:0] add_signext_213; // sfix33_En27
  wire signed [33:0] add_temp_50; // sfix34_En27
  wire signed [32:0] sum52; // sfix33_En27
  wire signed [32:0] add_signext_214; // sfix33_En27
  wire signed [32:0] add_signext_215; // sfix33_En27
  wire signed [33:0] add_temp_51; // sfix34_En27
  wire signed [32:0] sum53; // sfix33_En27
  wire signed [32:0] add_signext_216; // sfix33_En27
  wire signed [32:0] add_signext_217; // sfix33_En27
  wire signed [33:0] add_temp_52; // sfix34_En27
  wire signed [32:0] sum54; // sfix33_En27
  wire signed [32:0] add_signext_218; // sfix33_En27
  wire signed [32:0] add_signext_219; // sfix33_En27
  wire signed [33:0] add_temp_53; // sfix34_En27
  wire signed [32:0] sum55; // sfix33_En27
  wire signed [32:0] add_signext_220; // sfix33_En27
  wire signed [32:0] add_signext_221; // sfix33_En27
  wire signed [33:0] add_temp_54; // sfix34_En27
  wire signed [32:0] sum56; // sfix33_En27
  wire signed [32:0] add_signext_222; // sfix33_En27
  wire signed [32:0] add_signext_223; // sfix33_En27
  wire signed [33:0] add_temp_55; // sfix34_En27
  reg  signed [32:0] output_register; // sfix33_En27



  assign add_signext = delay_pipeline[3];
  assign add_signext_1 = delay_pipeline[115];
  assign tapsum4 = add_signext + add_signext_1;

  assign tapsum_mcand = tapsum4;

  assign add_signext_2 = delay_pipeline[4];
  assign add_signext_3 = delay_pipeline[114];
  assign tapsum5 = add_signext_2 + add_signext_3;

  assign tapsum_mcand_1 = tapsum5;

  assign add_signext_4 = delay_pipeline[5];
  assign add_signext_5 = delay_pipeline[113];
  assign tapsum6 = add_signext_4 + add_signext_5;

  assign tapsum_mcand_2 = tapsum6;

  assign add_signext_6 = delay_pipeline[6];
  assign add_signext_7 = delay_pipeline[112];
  assign tapsum7 = add_signext_6 + add_signext_7;

  assign tapsum_mcand_3 = tapsum7;

  assign add_signext_8 = delay_pipeline[7];
  assign add_signext_9 = delay_pipeline[111];
  assign tapsum8 = add_signext_8 + add_signext_9;

  assign tapsum_mcand_4 = tapsum8;

  assign add_signext_10 = delay_pipeline[8];
  assign add_signext_11 = delay_pipeline[110];
  assign tapsum9 = add_signext_10 + add_signext_11;

  assign tapsum_mcand_5 = tapsum9;

  assign add_signext_12 = delay_pipeline[9];
  assign add_signext_13 = delay_pipeline[109];
  assign tapsum10 = add_signext_12 + add_signext_13;

  assign tapsum_mcand_6 = tapsum10;

  assign add_signext_14 = delay_pipeline[10];
  assign add_signext_15 = delay_pipeline[108];
  assign tapsum11 = add_signext_14 + add_signext_15;

  assign tapsum_mcand_7 = tapsum11;

  assign add_signext_16 = delay_pipeline[11];
  assign add_signext_17 = delay_pipeline[107];
  assign tapsum12 = add_signext_16 + add_signext_17;

  assign tapsum_mcand_8 = tapsum12;

  assign add_signext_18 = delay_pipeline[12];
  assign add_signext_19 = delay_pipeline[106];
  assign tapsum13 = add_signext_18 + add_signext_19;

  assign tapsum_mcand_9 = tapsum13;

  assign add_signext_20 = delay_pipeline[13];
  assign add_signext_21 = delay_pipeline[105];
  assign tapsum14 = add_signext_20 + add_signext_21;

  assign tapsum_mcand_10 = tapsum14;

  assign add_signext_22 = delay_pipeline[14];
  assign add_signext_23 = delay_pipeline[104];
  assign tapsum15 = add_signext_22 + add_signext_23;

  assign tapsum_mcand_11 = tapsum15;

  assign add_signext_24 = delay_pipeline[15];
  assign add_signext_25 = delay_pipeline[103];
  assign tapsum16 = add_signext_24 + add_signext_25;

  assign tapsum_mcand_12 = tapsum16;

  assign add_signext_26 = delay_pipeline[16];
  assign add_signext_27 = delay_pipeline[102];
  assign tapsum17 = add_signext_26 + add_signext_27;

  assign tapsum_mcand_13 = tapsum17;

  assign add_signext_28 = delay_pipeline[17];
  assign add_signext_29 = delay_pipeline[101];
  assign tapsum18 = add_signext_28 + add_signext_29;

  assign tapsum_mcand_14 = tapsum18;

  assign add_signext_30 = delay_pipeline[18];
  assign add_signext_31 = delay_pipeline[100];
  assign tapsum19 = add_signext_30 + add_signext_31;

  assign tapsum_mcand_15 = tapsum19;

  assign add_signext_32 = delay_pipeline[19];
  assign add_signext_33 = delay_pipeline[99];
  assign tapsum20 = add_signext_32 + add_signext_33;

  assign tapsum_mcand_16 = tapsum20;

  assign add_signext_34 = delay_pipeline[20];
  assign add_signext_35 = delay_pipeline[98];
  assign tapsum21 = add_signext_34 + add_signext_35;

  assign tapsum_mcand_17 = tapsum21;

  assign add_signext_36 = delay_pipeline[21];
  assign add_signext_37 = delay_pipeline[97];
  assign tapsum22 = add_signext_36 + add_signext_37;

  assign tapsum_mcand_18 = tapsum22;

  assign add_signext_38 = delay_pipeline[22];
  assign add_signext_39 = delay_pipeline[96];
  assign tapsum23 = add_signext_38 + add_signext_39;

  assign tapsum_mcand_19 = tapsum23;

  assign add_signext_40 = delay_pipeline[23];
  assign add_signext_41 = delay_pipeline[95];
  assign tapsum24 = add_signext_40 + add_signext_41;

  assign tapsum_mcand_20 = tapsum24;

  assign add_signext_42 = delay_pipeline[24];
  assign add_signext_43 = delay_pipeline[94];
  assign tapsum25 = add_signext_42 + add_signext_43;

  assign tapsum_mcand_21 = tapsum25;

  assign add_signext_44 = delay_pipeline[25];
  assign add_signext_45 = delay_pipeline[93];
  assign tapsum26 = add_signext_44 + add_signext_45;

  assign tapsum_mcand_22 = tapsum26;

  assign add_signext_46 = delay_pipeline[26];
  assign add_signext_47 = delay_pipeline[92];
  assign tapsum27 = add_signext_46 + add_signext_47;

  assign tapsum_mcand_23 = tapsum27;

  assign add_signext_48 = delay_pipeline[27];
  assign add_signext_49 = delay_pipeline[91];
  assign tapsum28 = add_signext_48 + add_signext_49;

  assign tapsum_mcand_24 = tapsum28;

  assign add_signext_50 = delay_pipeline[28];
  assign add_signext_51 = delay_pipeline[90];
  assign tapsum29 = add_signext_50 + add_signext_51;

  assign tapsum_mcand_25 = tapsum29;

  assign add_signext_52 = delay_pipeline[29];
  assign add_signext_53 = delay_pipeline[89];
  assign tapsum30 = add_signext_52 + add_signext_53;

  assign tapsum_mcand_26 = tapsum30;

  assign add_signext_54 = delay_pipeline[30];
  assign add_signext_55 = delay_pipeline[88];
  assign tapsum31 = add_signext_54 + add_signext_55;

  assign tapsum_mcand_27 = tapsum31;

  assign add_signext_56 = delay_pipeline[31];
  assign add_signext_57 = delay_pipeline[87];
  assign tapsum32 = add_signext_56 + add_signext_57;

  assign tapsum_mcand_28 = tapsum32;

  assign add_signext_58 = delay_pipeline[32];
  assign add_signext_59 = delay_pipeline[86];
  assign tapsum33 = add_signext_58 + add_signext_59;

  assign tapsum_mcand_29 = tapsum33;

  assign add_signext_60 = delay_pipeline[33];
  assign add_signext_61 = delay_pipeline[85];
  assign tapsum34 = add_signext_60 + add_signext_61;

  assign tapsum_mcand_30 = tapsum34;

  assign add_signext_62 = delay_pipeline[34];
  assign add_signext_63 = delay_pipeline[84];
  assign tapsum35 = add_signext_62 + add_signext_63;

  assign tapsum_mcand_31 = tapsum35;

  assign add_signext_64 = delay_pipeline[35];
  assign add_signext_65 = delay_pipeline[83];
  assign tapsum36 = add_signext_64 + add_signext_65;

  assign tapsum_mcand_32 = tapsum36;

  assign add_signext_66 = delay_pipeline[36];
  assign add_signext_67 = delay_pipeline[82];
  assign tapsum37 = add_signext_66 + add_signext_67;

  assign tapsum_mcand_33 = tapsum37;

  assign add_signext_68 = delay_pipeline[37];
  assign add_signext_69 = delay_pipeline[81];
  assign tapsum38 = add_signext_68 + add_signext_69;

  assign tapsum_mcand_34 = tapsum38;

  assign add_signext_70 = delay_pipeline[38];
  assign add_signext_71 = delay_pipeline[80];
  assign tapsum39 = add_signext_70 + add_signext_71;

  assign tapsum_mcand_35 = tapsum39;

  assign add_signext_72 = delay_pipeline[39];
  assign add_signext_73 = delay_pipeline[79];
  assign tapsum40 = add_signext_72 + add_signext_73;

  assign tapsum_mcand_36 = tapsum40;

  assign add_signext_74 = delay_pipeline[40];
  assign add_signext_75 = delay_pipeline[78];
  assign tapsum41 = add_signext_74 + add_signext_75;

  assign tapsum_mcand_37 = tapsum41;

  assign add_signext_76 = delay_pipeline[41];
  assign add_signext_77 = delay_pipeline[77];
  assign tapsum42 = add_signext_76 + add_signext_77;

  assign tapsum_mcand_38 = tapsum42;

  assign add_signext_78 = delay_pipeline[42];
  assign add_signext_79 = delay_pipeline[76];
  assign tapsum43 = add_signext_78 + add_signext_79;

  assign tapsum_mcand_39 = tapsum43;

  assign add_signext_80 = delay_pipeline[43];
  assign add_signext_81 = delay_pipeline[75];
  assign tapsum44 = add_signext_80 + add_signext_81;

  assign tapsum_mcand_40 = tapsum44;

  assign add_signext_82 = delay_pipeline[44];
  assign add_signext_83 = delay_pipeline[74];
  assign tapsum45 = add_signext_82 + add_signext_83;

  assign tapsum_mcand_41 = tapsum45;

  assign add_signext_84 = delay_pipeline[45];
  assign add_signext_85 = delay_pipeline[73];
  assign tapsum46 = add_signext_84 + add_signext_85;

  assign tapsum_mcand_42 = tapsum46;

  assign add_signext_86 = delay_pipeline[46];
  assign add_signext_87 = delay_pipeline[72];
  assign tapsum47 = add_signext_86 + add_signext_87;

  assign tapsum_mcand_43 = tapsum47;

  assign add_signext_88 = delay_pipeline[47];
  assign add_signext_89 = delay_pipeline[71];
  assign tapsum48 = add_signext_88 + add_signext_89;

  assign tapsum_mcand_44 = tapsum48;

  assign add_signext_90 = delay_pipeline[48];
  assign add_signext_91 = delay_pipeline[70];
  assign tapsum49 = add_signext_90 + add_signext_91;

  assign tapsum_mcand_45 = tapsum49;

  assign add_signext_92 = delay_pipeline[49];
  assign add_signext_93 = delay_pipeline[69];
  assign tapsum50 = add_signext_92 + add_signext_93;

  assign tapsum_mcand_46 = tapsum50;

  assign add_signext_94 = delay_pipeline[50];
  assign add_signext_95 = delay_pipeline[68];
  assign tapsum51 = add_signext_94 + add_signext_95;

  assign tapsum_mcand_47 = tapsum51;

  assign add_signext_96 = delay_pipeline[51];
  assign add_signext_97 = delay_pipeline[67];
  assign tapsum52 = add_signext_96 + add_signext_97;

  assign tapsum_mcand_48 = tapsum52;

  assign add_signext_98 = delay_pipeline[52];
  assign add_signext_99 = delay_pipeline[66];
  assign tapsum53 = add_signext_98 + add_signext_99;

  assign tapsum_mcand_49 = tapsum53;

  assign add_signext_100 = delay_pipeline[53];
  assign add_signext_101 = delay_pipeline[65];
  assign tapsum54 = add_signext_100 + add_signext_101;

  assign tapsum_mcand_50 = tapsum54;

  assign add_signext_102 = delay_pipeline[54];
  assign add_signext_103 = delay_pipeline[64];
  assign tapsum55 = add_signext_102 + add_signext_103;

  assign tapsum_mcand_51 = tapsum55;

  assign add_signext_104 = delay_pipeline[55];
  assign add_signext_105 = delay_pipeline[63];
  assign tapsum56 = add_signext_104 + add_signext_105;

  assign tapsum_mcand_52 = tapsum56;

  assign add_signext_106 = delay_pipeline[56];
  assign add_signext_107 = delay_pipeline[62];
  assign tapsum57 = add_signext_106 + add_signext_107;

  assign tapsum_mcand_53 = tapsum57;

  assign add_signext_108 = delay_pipeline[57];
  assign add_signext_109 = delay_pipeline[61];
  assign tapsum58 = add_signext_108 + add_signext_109;

  assign tapsum_mcand_54 = tapsum58;

  assign add_signext_110 = delay_pipeline[58];
  assign add_signext_111 = delay_pipeline[60];
  assign tapsum59 = add_signext_110 + add_signext_111;

  assign tapsum_mcand_55 = tapsum59;

  assign mul_temp = delay_pipeline[59] * coeff60;
  assign product60 = $signed({{1{mul_temp[25]}}, mul_temp});

  assign product59 = tapsum_mcand_55 * coeff59;

  assign product58 = tapsum_mcand_54 * coeff58;

  assign product57 = tapsum_mcand_53 * coeff57;

  assign product56 = tapsum_mcand_52 * coeff56;

  assign product55 = tapsum_mcand_51 * coeff55;

  assign product54 = tapsum_mcand_50 * coeff54;

  assign product53 = tapsum_mcand_49 * coeff53;

  assign product52 = tapsum_mcand_48 * coeff52;

  assign product51 = tapsum_mcand_47 * coeff51;

  assign product50 = tapsum_mcand_46 * coeff50;

  assign product49 = tapsum_mcand_45 * coeff49;

  assign product48 = tapsum_mcand_44 * coeff48;

  assign product47 = tapsum_mcand_43 * coeff47;

  assign product46 = tapsum_mcand_42 * coeff46;

  assign product45 = tapsum_mcand_41 * coeff45;

  assign product44 = tapsum_mcand_40 * coeff44;

  assign product43 = tapsum_mcand_39 * coeff43;

  assign product42 = tapsum_mcand_38 * coeff42;

  assign product41 = tapsum_mcand_37 * coeff41;

  assign product40 = tapsum_mcand_36 * coeff40;

  assign product39 = tapsum_mcand_35 * coeff39;

  assign product38 = tapsum_mcand_34 * coeff38;

  assign product37 = tapsum_mcand_33 * coeff37;

  assign product36 = tapsum_mcand_32 * coeff36;

  assign product35 = tapsum_mcand_31 * coeff35;

  assign product34 = tapsum_mcand_30 * coeff34;

  assign product33 = tapsum_mcand_29 * coeff33;

  assign product32 = tapsum_mcand_28 * coeff32;

  assign product31 = $signed({{13{tapsum_mcand_27[13]}}, tapsum_mcand_27});

  assign product30 = tapsum_mcand_26 * coeff30;

  assign product29 = tapsum_mcand_25 * coeff29;

  assign product28 = tapsum_mcand_24 * coeff28;

  assign product27 = tapsum_mcand_23 * coeff27;

  assign product26 = tapsum_mcand_22 * coeff26;

  assign product25 = tapsum_mcand_21 * coeff25;

  assign product24 = tapsum_mcand_20 * coeff24;

  assign product23 = tapsum_mcand_19 * coeff23;

  assign product22 = tapsum_mcand_18 * coeff22;

  assign product21 = tapsum_mcand_17 * coeff21;

  assign product20 = tapsum_mcand_16 * coeff20;

  assign product19 = tapsum_mcand_15 * coeff19;

  assign product18 = tapsum_mcand_14 * coeff18;

  assign product17 = tapsum_mcand_13 * coeff17;

  assign product16 = tapsum_mcand_12 * coeff16;

  assign product15 = tapsum_mcand_11 * coeff15;

  assign product14 = tapsum_mcand_10 * coeff14;

  assign product13 = tapsum_mcand_9 * coeff13;

  assign product12 = $signed({tapsum_mcand_8[13:0], 3'b000});

  assign product11 = tapsum_mcand_7 * coeff11;

  assign product10 = tapsum_mcand_6 * coeff10;

  assign product9 = tapsum_mcand_5 * coeff9;

  assign product8 = tapsum_mcand_4 * coeff8;

  assign product7 = $signed({tapsum_mcand_3[13:0], 3'b000});

  assign product6 = tapsum_mcand_2 * coeff6;

  assign mulpwr2_temp = (tapsum_mcand_1==14'b10000000000000) ? $signed({1'b0, tapsum_mcand_1}) : -tapsum_mcand_1;

  assign product5 = $signed({{12{mulpwr2_temp[14]}}, mulpwr2_temp});

  assign product4 = tapsum_mcand * coeff4;

  assign add_signext_112 = product4;
  assign add_signext_113 = product5;
  assign add_temp = add_signext_112 + add_signext_113;
  assign sum1 = $signed({{5{add_temp[27]}}, add_temp});

  assign add_signext_114 = sum1;
  assign add_signext_115 = $signed({{6{product6[26]}}, product6});
  assign add_temp_1 = add_signext_114 + add_signext_115;
  assign sum2 = add_temp_1[32:0];

  assign add_signext_116 = sum2;
  assign add_signext_117 = $signed({{6{product7[26]}}, product7});
  assign add_temp_2 = add_signext_116 + add_signext_117;
  assign sum3 = add_temp_2[32:0];

  assign add_signext_118 = sum3;
  assign add_signext_119 = $signed({{6{product8[26]}}, product8});
  assign add_temp_3 = add_signext_118 + add_signext_119;
  assign sum4 = add_temp_3[32:0];

  assign add_signext_120 = sum4;
  assign add_signext_121 = $signed({{6{product9[26]}}, product9});
  assign add_temp_4 = add_signext_120 + add_signext_121;
  assign sum5 = add_temp_4[32:0];

  assign add_signext_122 = sum5;
  assign add_signext_123 = $signed({{6{product10[26]}}, product10});
  assign add_temp_5 = add_signext_122 + add_signext_123;
  assign sum6 = add_temp_5[32:0];

  assign add_signext_124 = sum6;
  assign add_signext_125 = $signed({{6{product11[26]}}, product11});
  assign add_temp_6 = add_signext_124 + add_signext_125;
  assign sum7 = add_temp_6[32:0];

  assign add_signext_126 = sum7;
  assign add_signext_127 = $signed({{6{product12[26]}}, product12});
  assign add_temp_7 = add_signext_126 + add_signext_127;
  assign sum8 = add_temp_7[32:0];

  assign add_signext_128 = sum8;
  assign add_signext_129 = $signed({{6{product13[26]}}, product13});
  assign add_temp_8 = add_signext_128 + add_signext_129;
  assign sum9 = add_temp_8[32:0];

  assign add_signext_130 = sum9;
  assign add_signext_131 = $signed({{6{product14[26]}}, product14});
  assign add_temp_9 = add_signext_130 + add_signext_131;
  assign sum10 = add_temp_9[32:0];

  assign add_signext_132 = sum10;
  assign add_signext_133 = $signed({{6{product15[26]}}, product15});
  assign add_temp_10 = add_signext_132 + add_signext_133;
  assign sum11 = add_temp_10[32:0];

  assign add_signext_134 = sum11;
  assign add_signext_135 = $signed({{6{product16[26]}}, product16});
  assign add_temp_11 = add_signext_134 + add_signext_135;
  assign sum12 = add_temp_11[32:0];

  assign add_signext_136 = sum12;
  assign add_signext_137 = $signed({{6{product17[26]}}, product17});
  assign add_temp_12 = add_signext_136 + add_signext_137;
  assign sum13 = add_temp_12[32:0];

  assign add_signext_138 = sum13;
  assign add_signext_139 = $signed({{6{product18[26]}}, product18});
  assign add_temp_13 = add_signext_138 + add_signext_139;
  assign sum14 = add_temp_13[32:0];

  assign add_signext_140 = sum14;
  assign add_signext_141 = $signed({{6{product19[26]}}, product19});
  assign add_temp_14 = add_signext_140 + add_signext_141;
  assign sum15 = add_temp_14[32:0];

  assign add_signext_142 = sum15;
  assign add_signext_143 = $signed({{6{product20[26]}}, product20});
  assign add_temp_15 = add_signext_142 + add_signext_143;
  assign sum16 = add_temp_15[32:0];

  assign add_signext_144 = sum16;
  assign add_signext_145 = $signed({{6{product21[26]}}, product21});
  assign add_temp_16 = add_signext_144 + add_signext_145;
  assign sum17 = add_temp_16[32:0];

  assign add_signext_146 = sum17;
  assign add_signext_147 = $signed({{6{product22[26]}}, product22});
  assign add_temp_17 = add_signext_146 + add_signext_147;
  assign sum18 = add_temp_17[32:0];

  assign add_signext_148 = sum18;
  assign add_signext_149 = $signed({{6{product23[26]}}, product23});
  assign add_temp_18 = add_signext_148 + add_signext_149;
  assign sum19 = add_temp_18[32:0];

  assign add_signext_150 = sum19;
  assign add_signext_151 = $signed({{6{product24[26]}}, product24});
  assign add_temp_19 = add_signext_150 + add_signext_151;
  assign sum20 = add_temp_19[32:0];

  assign add_signext_152 = sum20;
  assign add_signext_153 = $signed({{6{product25[26]}}, product25});
  assign add_temp_20 = add_signext_152 + add_signext_153;
  assign sum21 = add_temp_20[32:0];

  assign add_signext_154 = sum21;
  assign add_signext_155 = $signed({{6{product26[26]}}, product26});
  assign add_temp_21 = add_signext_154 + add_signext_155;
  assign sum22 = add_temp_21[32:0];

  assign add_signext_156 = sum22;
  assign add_signext_157 = $signed({{6{product27[26]}}, product27});
  assign add_temp_22 = add_signext_156 + add_signext_157;
  assign sum23 = add_temp_22[32:0];

  assign add_signext_158 = sum23;
  assign add_signext_159 = $signed({{6{product28[26]}}, product28});
  assign add_temp_23 = add_signext_158 + add_signext_159;
  assign sum24 = add_temp_23[32:0];

  assign add_signext_160 = sum24;
  assign add_signext_161 = $signed({{6{product29[26]}}, product29});
  assign add_temp_24 = add_signext_160 + add_signext_161;
  assign sum25 = add_temp_24[32:0];

  assign add_signext_162 = sum25;
  assign add_signext_163 = $signed({{6{product30[26]}}, product30});
  assign add_temp_25 = add_signext_162 + add_signext_163;
  assign sum26 = add_temp_25[32:0];

  assign add_signext_164 = sum26;
  assign add_signext_165 = $signed({{6{product31[26]}}, product31});
  assign add_temp_26 = add_signext_164 + add_signext_165;
  assign sum27 = add_temp_26[32:0];

  assign add_signext_166 = sum27;
  assign add_signext_167 = $signed({{6{product32[26]}}, product32});
  assign add_temp_27 = add_signext_166 + add_signext_167;
  assign sum28 = add_temp_27[32:0];

  assign add_signext_168 = sum28;
  assign add_signext_169 = $signed({{6{product33[26]}}, product33});
  assign add_temp_28 = add_signext_168 + add_signext_169;
  assign sum29 = add_temp_28[32:0];

  assign add_signext_170 = sum29;
  assign add_signext_171 = $signed({{6{product34[26]}}, product34});
  assign add_temp_29 = add_signext_170 + add_signext_171;
  assign sum30 = add_temp_29[32:0];

  assign add_signext_172 = sum30;
  assign add_signext_173 = $signed({{6{product35[26]}}, product35});
  assign add_temp_30 = add_signext_172 + add_signext_173;
  assign sum31 = add_temp_30[32:0];

  assign add_signext_174 = sum31;
  assign add_signext_175 = $signed({{6{product36[26]}}, product36});
  assign add_temp_31 = add_signext_174 + add_signext_175;
  assign sum32 = add_temp_31[32:0];

  assign add_signext_176 = sum32;
  assign add_signext_177 = $signed({{6{product37[26]}}, product37});
  assign add_temp_32 = add_signext_176 + add_signext_177;
  assign sum33 = add_temp_32[32:0];

  assign add_signext_178 = sum33;
  assign add_signext_179 = $signed({{6{product38[26]}}, product38});
  assign add_temp_33 = add_signext_178 + add_signext_179;
  assign sum34 = add_temp_33[32:0];

  assign add_signext_180 = sum34;
  assign add_signext_181 = $signed({{6{product39[26]}}, product39});
  assign add_temp_34 = add_signext_180 + add_signext_181;
  assign sum35 = add_temp_34[32:0];

  assign add_signext_182 = sum35;
  assign add_signext_183 = $signed({{6{product40[26]}}, product40});
  assign add_temp_35 = add_signext_182 + add_signext_183;
  assign sum36 = add_temp_35[32:0];

  assign add_signext_184 = sum36;
  assign add_signext_185 = $signed({{6{product41[26]}}, product41});
  assign add_temp_36 = add_signext_184 + add_signext_185;
  assign sum37 = add_temp_36[32:0];

  assign add_signext_186 = sum37;
  assign add_signext_187 = $signed({{6{product42[26]}}, product42});
  assign add_temp_37 = add_signext_186 + add_signext_187;
  assign sum38 = add_temp_37[32:0];

  assign add_signext_188 = sum38;
  assign add_signext_189 = $signed({{6{product43[26]}}, product43});
  assign add_temp_38 = add_signext_188 + add_signext_189;
  assign sum39 = add_temp_38[32:0];

  assign add_signext_190 = sum39;
  assign add_signext_191 = $signed({{6{product44[26]}}, product44});
  assign add_temp_39 = add_signext_190 + add_signext_191;
  assign sum40 = add_temp_39[32:0];

  assign add_signext_192 = sum40;
  assign add_signext_193 = $signed({{6{product45[26]}}, product45});
  assign add_temp_40 = add_signext_192 + add_signext_193;
  assign sum41 = add_temp_40[32:0];

  assign add_signext_194 = sum41;
  assign add_signext_195 = $signed({{6{product46[26]}}, product46});
  assign add_temp_41 = add_signext_194 + add_signext_195;
  assign sum42 = add_temp_41[32:0];

  assign add_signext_196 = sum42;
  assign add_signext_197 = $signed({{6{product47[26]}}, product47});
  assign add_temp_42 = add_signext_196 + add_signext_197;
  assign sum43 = add_temp_42[32:0];

  assign add_signext_198 = sum43;
  assign add_signext_199 = $signed({{6{product48[26]}}, product48});
  assign add_temp_43 = add_signext_198 + add_signext_199;
  assign sum44 = add_temp_43[32:0];

  assign add_signext_200 = sum44;
  assign add_signext_201 = $signed({{6{product49[26]}}, product49});
  assign add_temp_44 = add_signext_200 + add_signext_201;
  assign sum45 = add_temp_44[32:0];

  assign add_signext_202 = sum45;
  assign add_signext_203 = $signed({{6{product50[26]}}, product50});
  assign add_temp_45 = add_signext_202 + add_signext_203;
  assign sum46 = add_temp_45[32:0];

  assign add_signext_204 = sum46;
  assign add_signext_205 = $signed({{6{product51[26]}}, product51});
  assign add_temp_46 = add_signext_204 + add_signext_205;
  assign sum47 = add_temp_46[32:0];

  assign add_signext_206 = sum47;
  assign add_signext_207 = $signed({{6{product52[26]}}, product52});
  assign add_temp_47 = add_signext_206 + add_signext_207;
  assign sum48 = add_temp_47[32:0];

  assign add_signext_208 = sum48;
  assign add_signext_209 = $signed({{6{product53[26]}}, product53});
  assign add_temp_48 = add_signext_208 + add_signext_209;
  assign sum49 = add_temp_48[32:0];

  assign add_signext_210 = sum49;
  assign add_signext_211 = $signed({{6{product54[26]}}, product54});
  assign add_temp_49 = add_signext_210 + add_signext_211;
  assign sum50 = add_temp_49[32:0];

  assign add_signext_212 = sum50;
  assign add_signext_213 = $signed({{6{product55[26]}}, product55});
  assign add_temp_50 = add_signext_212 + add_signext_213;
  assign sum51 = add_temp_50[32:0];

  assign add_signext_214 = sum51;
  assign add_signext_215 = $signed({{6{product56[26]}}, product56});
  assign add_temp_51 = add_signext_214 + add_signext_215;
  assign sum52 = add_temp_51[32:0];

  assign add_signext_216 = sum52;
  assign add_signext_217 = $signed({{6{product57[26]}}, product57});
  assign add_temp_52 = add_signext_216 + add_signext_217;
  assign sum53 = add_temp_52[32:0];

  assign add_signext_218 = sum53;
  assign add_signext_219 = $signed({{6{product58[26]}}, product58});
  assign add_temp_53 = add_signext_218 + add_signext_219;
  assign sum54 = add_temp_53[32:0];

  assign add_signext_220 = sum54;
  assign add_signext_221 = $signed({{6{product59[26]}}, product59});
  assign add_temp_54 = add_signext_220 + add_signext_221;
  assign sum55 = add_temp_54[32:0];

  assign add_signext_222 = sum55;
  assign add_signext_223 = $signed({{6{product60[26]}}, product60});
  assign add_temp_55 = add_signext_222 + add_signext_223;
  assign sum56 = add_temp_55[32:0];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum56;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter12
